###############################################################################
# Policy: Developer
# -----------------
# A developer role can:
# - Deploy canary functions that use CodeDeploy.
###############################################################################
resource "aws_iam_policy" "developer" {
  name   = "${local.tf_group_developer_name}-canary"
  path   = "/"
  policy = "${data.aws_iam_policy_document.developer.json}"
}

locals {
  codedeploy_application_name = "sls-${local.service_name}-${local.iam_stage}-Sls${replace(local.service_name, "-", "")}${local.iam_stage}DeploymentApplication"
}

data "aws_iam_policy_document" "developer" {
  statement {
    actions = [
      "codedeploy:CreateApplication",
      "codedeploy:DeleteApplication",
      "codedeploy:GetApplication",
      "codedeploy:GetApplicationRevision",
      "codedeploy:RegisterApplicationRevision",
      "codedeploy:UpdateApplication",
    ]

    # Autogenerated name from serverless-plugin-canary-deployments
    # https://github.com/davidgf/serverless-plugin-canary-deployments/blob/9afaefa996c1e9233f8d7f64529f6c69754644a0/serverless-plugin-canary-deployments.js#L20
    resources = [
      "arn:${local.iam_partition}:codedeploy:${local.iam_region}:${local.iam_account_id}:application:${local.codedeploy_application_name}-*",
    ]
  }

  statement {
    actions = [
      "codedeploy:ContinueDeployment",
      "codedeploy:CreateDeploymentGroup",
      "codedeploy:CreateDeployment",
      "codedeploy:DeleteDeploymentGroup",
      "codedeploy:GetDeployment",
      "codedeploy:GetDeploymentGroup",
      "codedeploy:ListDeploymentGroups",
      "codedeploy:ListDeployments",
      "codedeploy:StopDeployment",
      "codedeploy:UpdateDeploymentGroup",
    ]

    # Autogenerated name from serverless-plugin-canary-deployments
    # https://github.com/davidgf/serverless-plugin-canary-deployments/blob/9afaefa996c1e9233f8d7f64529f6c69754644a0/serverless-plugin-canary-deployments.js#L20
    resources = [
      "arn:${local.iam_partition}:codedeploy:${local.iam_region}:${local.iam_account_id}:deploymentgroup:${local.codedeploy_application_name}-*/sls-${local.service_name}-${local.iam_stage}-*LambdaFunctionDeploymentGroup-*",
    ]
  }

  # Allow access to all default CodeDeploy deployment configs
  statement {
    actions = ["codedeploy:GetDeploymentConfig"]

    resources = ["arn:${local.iam_partition}:codedeploy:${local.iam_region}:${local.iam_account_id}:deploymentconfig:CodeDeployDefault.*"]
  }
}
